{
//=========Macro generated from canvas: c1/c1
//=========  (Wed Feb 12 21:48:06 2014) by ROOT version5.34/13
   TCanvas *c1 = new TCanvas("c1", "c1",0,22,500,400);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->SetHighLightColor(2);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: pad1
   TPad *pad1 = new TPad("pad1", "pad1",0,0.25,1,1);
   pad1->Draw();
   pad1->cd();
   pad1->Range(0.4375,-0.30103,4.1875,5.279002);
   pad1->SetFillColor(0);
   pad1->SetBorderMode(0);
   pad1->SetBorderSize(2);
   pad1->SetLogy();
   pad1->SetLeftMargin(0.15);
   pad1->SetRightMargin(0.05);
   pad1->SetTopMargin(0.05);
   pad1->SetBottomMargin(0);
   pad1->SetFrameBorderMode(0);
   pad1->SetFrameBorderMode(0);
   Double_t xAxis19[4] = {1, 2, 3, 4}; 
   
   TH1D *histoToy_nBtag_FULL_ALLCOMPONENTSCOPY = new TH1D("histoToy_nBtag_FULL_ALLCOMPONENTSCOPY","histoToy",3, xAxis19);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetBinContent(1,1414.98);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetBinContent(2,1575.8);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetBinContent(3,338.2);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetBinError(1,45.91247);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetBinError(2,52.0198);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetBinError(3,19.53485);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetMinimum(0.5);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetMaximum(100000);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetEntries(166449);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ccccff");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetLineColor(ci);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetLineWidth(2);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetBinLabel(1,"1");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetBinLabel(2,"2");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetBinLabel(3,"#geq 3");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetRange(1,3);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetLabelFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetLabelOffset(0.16);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetLabelSize(0.06);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetTitleSize(0.06);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetTitleOffset(0.8);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetTitleFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetTitle("Events");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetLabelFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetLabelSize(0.06);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetTitleSize(0.08);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetTitleOffset(0.7);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetTitleFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetZaxis()->SetLabelFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetZaxis()->SetLabelSize(0.035);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetZaxis()->SetTitleSize(0.035);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetZaxis()->SetTitleFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->Draw("e2");
   Double_t xAxis20[4] = {1, 2, 3, 4}; 
   
   TH1D *histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS = new TH1D("histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS","histoToyTTj2b",3, xAxis20);
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->SetBinContent(2,1575.8);
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->SetBinContent(3,338.2);
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->SetBinError(1,1);
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->SetBinError(2,39.69635);
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->SetBinError(3,18.39021);
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->SetEntries(95700);
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->SetStats(0);

   ci = TColor::GetColor("#ff3333");
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->SetLineColor(ci);
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->SetLineWidth(2);
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetTitle("n_{b-tag}");
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetBinLabel(1,"1");
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetBinLabel(2,"2");
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetBinLabel(3,"#geq 3");
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->GetYaxis()->SetTitle("Events");
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS->Draw("histsame");
   Double_t xAxis21[4] = {1, 2, 3, 4}; 
   
   TH1D *histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS = new TH1D("histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS","histoToyTTj1b",3, xAxis21);
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->SetBinContent(1,1414.98);
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->SetBinError(1,37.61622);
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->SetBinError(2,1);
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->SetBinError(3,1);
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->SetEntries(70749);
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->SetStats(0);

   ci = TColor::GetColor("#cc66ff");
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->SetFillColor(ci);

   ci = TColor::GetColor("#cc00ff");
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->SetLineColor(ci);
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->SetLineWidth(2);
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetTitle("n_{b-tag}");
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetBinLabel(1,"1");
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetBinLabel(2,"2");
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetBinLabel(3,"#geq 3");
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->GetYaxis()->SetTitle("Events");
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS->Draw("histsame");
   Double_t xAxis22[4] = {1, 2, 3, 4}; 
   
   TH1D *histoToy_nBtag_FULL_ALLCOMPONENTSCOPY = new TH1D("histoToy_nBtag_FULL_ALLCOMPONENTSCOPY","histoToy",3, xAxis22);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetBinContent(1,1414.98);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetBinContent(2,1575.8);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetBinContent(3,338.2);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetBinError(1,45.91247);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetBinError(2,52.0198);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetBinError(3,19.53485);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetMinimum(0.5);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetMaximum(100000);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetEntries(166449);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetStats(0);

   ci = TColor::GetColor("#ccccff");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetLineColor(ci);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->SetLineWidth(2);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetBinLabel(1,"1");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetBinLabel(2,"2");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetBinLabel(3,"#geq 3");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetRange(1,3);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetLabelFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetLabelOffset(0.16);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetLabelSize(0.06);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetTitleSize(0.06);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetTitleOffset(0.8);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetTitleFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetTitle("Events");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetLabelFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetLabelSize(0.06);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetTitleSize(0.08);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetTitleOffset(0.7);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetTitleFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetZaxis()->SetLabelFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetZaxis()->SetLabelSize(0.035);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetZaxis()->SetTitleSize(0.035);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->GetZaxis()->SetTitleFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPY->Draw("e2same");
   Double_t xAxis23[4] = {1, 2, 3, 4}; 
   
   TH1D *histoData_nBtag_FULL_ALLCOMPONENTS = new TH1D("histoData_nBtag_FULL_ALLCOMPONENTS","histoData",3, xAxis23);
   histoData_nBtag_FULL_ALLCOMPONENTS->SetBinContent(1,1415);
   histoData_nBtag_FULL_ALLCOMPONENTS->SetBinContent(2,1576);
   histoData_nBtag_FULL_ALLCOMPONENTS->SetBinContent(3,338);
   histoData_nBtag_FULL_ALLCOMPONENTS->SetBinError(1,37.61649);
   histoData_nBtag_FULL_ALLCOMPONENTS->SetBinError(2,39.69887);
   histoData_nBtag_FULL_ALLCOMPONENTS->SetBinError(3,18.38478);
   histoData_nBtag_FULL_ALLCOMPONENTS->SetEntries(3329);
   histoData_nBtag_FULL_ALLCOMPONENTS->SetStats(0);
   histoData_nBtag_FULL_ALLCOMPONENTS->SetLineWidth(2);
   histoData_nBtag_FULL_ALLCOMPONENTS->SetMarkerStyle(20);
   histoData_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetTitle("n_{b-tag}");
   histoData_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetBinLabel(1,"1");
   histoData_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetBinLabel(2,"2");
   histoData_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetBinLabel(3,"#geq 3");
   histoData_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetRange(1,3);
   histoData_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoData_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoData_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoData_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoData_nBtag_FULL_ALLCOMPONENTS->GetYaxis()->SetTitle("Events");
   histoData_nBtag_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoData_nBtag_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoData_nBtag_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoData_nBtag_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoData_nBtag_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoData_nBtag_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoData_nBtag_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoData_nBtag_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoData_nBtag_FULL_ALLCOMPONENTS->Draw("pesame");
   Double_t xAxis24[4] = {1, 2, 3, 4}; 
   
   TH1D *histoToy_nBtag_FULL_ALLCOMPONENTS__3 = new TH1D("histoToy_nBtag_FULL_ALLCOMPONENTS__3","histoToy",3, xAxis24);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->SetBinContent(1,1414.98);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->SetBinContent(2,1575.8);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->SetBinContent(3,338.2);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->SetMinimum(0.5);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->SetMaximum(50000);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->SetEntries(166449);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->SetDirectory(0);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->SetStats(0);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->SetFillStyle(0);

   ci = TColor::GetColor("#000099");
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->SetLineColor(ci);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->SetLineWidth(2);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->GetXaxis()->SetBinLabel(1,"1");
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->GetXaxis()->SetBinLabel(2,"2");
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->GetXaxis()->SetBinLabel(3,"#geq 3");
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->GetXaxis()->SetRange(1,3);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->GetXaxis()->SetLabelFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->GetXaxis()->SetLabelSize(0.035);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->GetXaxis()->SetTitleSize(0.035);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->GetXaxis()->SetTitleFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->GetYaxis()->SetTitle("Events");
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->GetYaxis()->SetLabelFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->GetYaxis()->SetLabelSize(0.035);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->GetYaxis()->SetTitleSize(0.035);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->GetYaxis()->SetTitleFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->GetZaxis()->SetLabelFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->GetZaxis()->SetLabelSize(0.035);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->GetZaxis()->SetTitleSize(0.035);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->GetZaxis()->SetTitleFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTS__3->Draw("histsame");
   Double_t xAxis25[4] = {1, 2, 3, 4}; 
   
   TH1D *histoToySignal_nBtag_FULL_ALLCOMPONENTS = new TH1D("histoToySignal_nBtag_FULL_ALLCOMPONENTS","histoToySignal",3, xAxis25);
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->SetStats(0);

   ci = TColor::GetColor("#666666");
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->SetFillColor(ci);
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->SetFillStyle(3005);
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->SetLineStyle(2);
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->SetLineWidth(2);
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetTitle("n_{b-tag}");
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetBinLabel(1,"1");
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetBinLabel(2,"2");
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetBinLabel(3,"#geq 3");
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->GetYaxis()->SetTitle("Events");
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoToySignal_nBtag_FULL_ALLCOMPONENTS->Draw("histfsame");
   
   TLegend *leg = new TLegend(0.7,0.55,0.93,0.93,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("histoData_nBtag_FULL_ALLCOMPONENTS","Simulated Data","lep");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("histoToy_nBtag_FULL_ALLCOMPONENTSCOPY","Bkgd, #geq 1 b-tag","lpf");

   ci = TColor::GetColor("#ccccff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("histoToyTTj1b_nBtag_FULL_ALLCOMPONENTS","1 b-tag","f");

   ci = TColor::GetColor("#cc66ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cc00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("histoToyTTj2b_nBtag_FULL_ALLCOMPONENTS","#geq 2 b-tag","f");

   ci = TColor::GetColor("#ff3333");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   TPaveText *pt = new TPaveText(0.25,0.67,0.7,0.93,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetLineColor(0);
   pt->SetTextAlign(21);
   pt->SetTextFont(42);
   pt->SetTextSize(0.062);
   TText *text = pt->AddText("CMS Simulation #sqrt{s} = 8 TeV");
   text = pt->AddText("t#bar{t}+jets BJetHS Box , #geq 1 b-tag");
   pt->Draw();
   pad1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: pad2
   pad2 = new TPad("pad2", "pad2",0,0,1,0.25);
   pad2->Draw();
   pad2->cd();
   pad2->Range(0.4375,-3.103774,4.1875,3.5);
   pad2->SetFillColor(0);
   pad2->SetBorderMode(0);
   pad2->SetBorderSize(2);
   pad2->SetLeftMargin(0.15);
   pad2->SetRightMargin(0.05);
   pad2->SetTopMargin(0);
   pad2->SetBottomMargin(0.47);
   pad2->SetFrameBorderMode(0);
   pad2->SetFrameBorderMode(0);
   Double_t xAxis26[4] = {1, 2, 3, 4}; 
   
   TH1D *histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide = new TH1D("histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide","",3, xAxis26);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(1,1);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(2,1);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(3,1);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(1,0.03244744);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(2,0.03301168);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(3,0.05776123);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetMinimum(0);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetMaximum(3.5);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetEntries(166452);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetStats(0);

   ci = TColor::GetColor("#ccccff");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetLineColor(ci);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetLineWidth(2);

   ci = TColor::GetColor("#ccccff");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetMarkerColor(ci);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitle("n_{b-tag}");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetBinLabel(1,"1");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetBinLabel(2,"2");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetBinLabel(3,"#geq 3");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetRange(1,3);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelOffset(0.02);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelSize(0.32);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleSize(0.22);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTickLength(0.07);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleOffset(0.97);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitle("Data/Bkgd");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetNdivisions(504);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelSize(0.18);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleSize(0.22);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleOffset(0.2);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelSize(0.035);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleSize(0.035);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->Draw("e2");
   Double_t xAxis27[4] = {1, 2, 3, 4}; 
   
   TH1D *histoData_nBtag_FULL_ALLCOMPONENTSDivide = new TH1D("histoData_nBtag_FULL_ALLCOMPONENTSDivide","histoData",3, xAxis27);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->SetBinContent(1,1.000014);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->SetBinContent(2,1.000127);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->SetBinContent(3,0.9994086);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->SetBinError(1,0.02658446);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->SetBinError(2,0.02519283);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->SetBinError(3,0.05436066);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->SetEntries(3332);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->SetStats(0);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->SetLineWidth(2);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->SetMarkerStyle(20);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->GetXaxis()->SetTitle("n_{b-tag}");
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->GetXaxis()->SetBinLabel(1,"1");
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->GetXaxis()->SetBinLabel(2,"2");
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->GetXaxis()->SetBinLabel(3,"#geq 3");
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->GetXaxis()->SetRange(1,3);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->GetXaxis()->SetLabelFont(42);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->GetXaxis()->SetLabelSize(0.035);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->GetXaxis()->SetTitleSize(0.035);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->GetXaxis()->SetTitleFont(42);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->GetYaxis()->SetTitle("Events");
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->GetYaxis()->SetLabelFont(42);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->GetYaxis()->SetLabelSize(0.035);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->GetYaxis()->SetTitleSize(0.035);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->GetYaxis()->SetTitleFont(42);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->GetZaxis()->SetLabelFont(42);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->GetZaxis()->SetLabelSize(0.035);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->GetZaxis()->SetTitleSize(0.035);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->GetZaxis()->SetTitleFont(42);
   histoData_nBtag_FULL_ALLCOMPONENTSDivide->Draw("pesame");
   Double_t xAxis28[4] = {1, 2, 3, 4}; 
   
   TH1D *histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide = new TH1D("histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide","",3, xAxis28);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(1,1);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(2,1);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(3,1);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(1,0.03244744);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(2,0.03301168);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(3,0.05776123);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetMinimum(0);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetMaximum(3.5);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetEntries(166452);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetStats(0);

   ci = TColor::GetColor("#ccccff");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetLineColor(ci);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetLineWidth(2);

   ci = TColor::GetColor("#ccccff");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->SetMarkerColor(ci);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitle("n_{b-tag}");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetBinLabel(1,"1");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetBinLabel(2,"2");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetBinLabel(3,"#geq 3");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetRange(1,3);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelOffset(0.02);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelSize(0.32);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleSize(0.22);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTickLength(0.07);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleOffset(0.97);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitle("Data/Bkgd");
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetNdivisions(504);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelSize(0.18);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleSize(0.22);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleOffset(0.2);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelSize(0.035);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleSize(0.035);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleFont(42);
   histoToy_nBtag_FULL_ALLCOMPONENTSCOPYDivide->Draw("axissame");
   pad2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
