{
//=========Macro generated from canvas: c1/c1
//=========  (Wed Feb 12 21:48:06 2014) by ROOT version5.34/13
   TCanvas *c1 = new TCanvas("c1", "c1",0,22,500,400);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->SetHighLightColor(2);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: pad1
   TPad *pad1 = new TPad("pad1", "pad1",0,0.25,1,1);
   pad1->Draw();
   pad1->cd();
   pad1->Range(-215.625,-1.30103,4221.875,3.921517);
   pad1->SetFillColor(0);
   pad1->SetBorderMode(0);
   pad1->SetBorderSize(2);
   pad1->SetLogy();
   pad1->SetLeftMargin(0.15);
   pad1->SetRightMargin(0.05);
   pad1->SetTopMargin(0.05);
   pad1->SetBottomMargin(0);
   pad1->SetFrameBorderMode(0);
   pad1->SetFrameBorderMode(0);
   Double_t xAxis1[8] = {450, 550, 700, 900, 1200, 1600, 2500, 4000}; 
   
   TH1D *histoToy_MR_FULL_ALLCOMPONENTSCOPY = new TH1D("histoToy_MR_FULL_ALLCOMPONENTSCOPY","histoToy",7, xAxis1);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->SetBinContent(1,1852.42);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->SetBinContent(2,997.14);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->SetBinContent(3,355.46);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->SetBinContent(4,103.78);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->SetBinContent(5,18.14);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->SetBinContent(6,2.02);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->SetBinContent(7,0.02);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->SetBinError(1,43.03975);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->SetBinError(2,87.92852);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->SetBinError(3,34.06569);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->SetBinError(4,20.22543);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->SetBinError(5,8.350017);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->SetBinError(6,2.444149);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->SetBinError(7,1);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->SetMinimum(0.05);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->SetMaximum(4574.981);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->SetEntries(166449);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ccccff");
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->SetLineColor(ci);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->SetLineWidth(2);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetRange(1,7);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetLabelFont(42);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetLabelOffset(0.16);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetLabelSize(0.06);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetTitleSize(0.06);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetTitleOffset(0.8);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetTitleFont(42);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetTitle("Events");
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetLabelFont(42);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetLabelSize(0.06);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetTitleSize(0.08);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetTitleOffset(0.7);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetTitleFont(42);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->GetZaxis()->SetLabelFont(42);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->GetZaxis()->SetLabelSize(0.035);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->GetZaxis()->SetTitleSize(0.035);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->GetZaxis()->SetTitleFont(42);
   histoToy_MR_FULL_ALLCOMPONENTSCOPY->Draw("e2");
   Double_t xAxis2[8] = {450, 550, 700, 900, 1200, 1600, 2500, 4000}; 
   
   TH1D *histoToyTTj2b_MR_FULL_ALLCOMPONENTS = new TH1D("histoToyTTj2b_MR_FULL_ALLCOMPONENTS","histoToyTTj2b",7, xAxis2);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->SetBinContent(1,1077.36);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->SetBinContent(2,572.9);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->SetBinContent(3,198.6);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->SetBinContent(4,54.86);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->SetBinContent(5,9.2);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->SetBinContent(6,1.06);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->SetBinContent(7,0.02);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->SetBinError(1,32.82316);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->SetBinError(2,23.93533);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->SetBinError(3,14.09255);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->SetBinError(4,7.406754);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->SetBinError(5,3.03315);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->SetBinError(6,1.029563);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->SetBinError(7,1);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->SetEntries(95700);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->SetStats(0);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->SetFillStyle(0);

   ci = TColor::GetColor("#ff0000");
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->SetLineColor(ci);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->SetLineWidth(2);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->GetXaxis()->SetTitle("M_{R} [GeV]");
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->GetYaxis()->SetTitle("Events/(100 GeV)");
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoToyTTj2b_MR_FULL_ALLCOMPONENTS->Draw("histsame");
   Double_t xAxis3[8] = {450, 550, 700, 900, 1200, 1600, 2500, 4000}; 
   
   TH1D *histoToyTTj1b_MR_FULL_ALLCOMPONENTS = new TH1D("histoToyTTj1b_MR_FULL_ALLCOMPONENTS","histoToyTTj1b",7, xAxis3);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->SetBinContent(1,775.06);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->SetBinContent(2,424.24);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->SetBinContent(3,156.86);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->SetBinContent(4,48.92);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->SetBinContent(5,8.94);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->SetBinContent(6,0.96);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->SetBinError(1,27.8399);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->SetBinError(2,20.59709);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->SetBinError(3,12.52438);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->SetBinError(4,6.994283);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->SetBinError(5,2.989983);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->SetBinError(6,1);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->SetBinError(7,1);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->SetEntries(70749);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->SetStats(0);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->SetFillStyle(0);

   ci = TColor::GetColor("#cc00ff");
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->SetLineColor(ci);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->SetLineWidth(2);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->GetXaxis()->SetTitle("M_{R} [GeV]");
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->GetYaxis()->SetTitle("Events/(100 GeV)");
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoToyTTj1b_MR_FULL_ALLCOMPONENTS->Draw("histsame");
   Double_t xAxis4[8] = {450, 550, 700, 900, 1200, 1600, 2500, 4000}; 
   
   TH1D *histoData_MR_FULL_ALLCOMPONENTS = new TH1D("histoData_MR_FULL_ALLCOMPONENTS","histoData",7, xAxis4);
   histoData_MR_FULL_ALLCOMPONENTS->SetBinContent(1,1795);
   histoData_MR_FULL_ALLCOMPONENTS->SetBinContent(2,1102);
   histoData_MR_FULL_ALLCOMPONENTS->SetBinContent(3,337);
   histoData_MR_FULL_ALLCOMPONENTS->SetBinContent(4,76);
   histoData_MR_FULL_ALLCOMPONENTS->SetBinContent(5,16);
   histoData_MR_FULL_ALLCOMPONENTS->SetBinContent(6,3);
   histoData_MR_FULL_ALLCOMPONENTS->SetBinError(1,42.36744);
   histoData_MR_FULL_ALLCOMPONENTS->SetBinError(2,33.19639);
   histoData_MR_FULL_ALLCOMPONENTS->SetBinError(3,18.35756);
   histoData_MR_FULL_ALLCOMPONENTS->SetBinError(4,8.717798);
   histoData_MR_FULL_ALLCOMPONENTS->SetBinError(5,4);
   histoData_MR_FULL_ALLCOMPONENTS->SetBinError(6,1.732051);
   histoData_MR_FULL_ALLCOMPONENTS->SetEntries(3329);
   histoData_MR_FULL_ALLCOMPONENTS->SetStats(0);
   histoData_MR_FULL_ALLCOMPONENTS->SetLineWidth(2);
   histoData_MR_FULL_ALLCOMPONENTS->SetMarkerStyle(20);
   histoData_MR_FULL_ALLCOMPONENTS->GetXaxis()->SetTitle("M_{R} [GeV]");
   histoData_MR_FULL_ALLCOMPONENTS->GetXaxis()->SetRange(1,7);
   histoData_MR_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoData_MR_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoData_MR_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoData_MR_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoData_MR_FULL_ALLCOMPONENTS->GetYaxis()->SetTitle("Events/(100 GeV)");
   histoData_MR_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoData_MR_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoData_MR_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoData_MR_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoData_MR_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoData_MR_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoData_MR_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoData_MR_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoData_MR_FULL_ALLCOMPONENTS->Draw("pesame");
   Double_t xAxis5[8] = {450, 550, 700, 900, 1200, 1600, 2500, 4000}; 
   
   TH1D *histoToy_MR_FULL_ALLCOMPONENTS__1 = new TH1D("histoToy_MR_FULL_ALLCOMPONENTS__1","histoToy",7, xAxis5);
   histoToy_MR_FULL_ALLCOMPONENTS__1->SetBinContent(1,1852.42);
   histoToy_MR_FULL_ALLCOMPONENTS__1->SetBinContent(2,997.14);
   histoToy_MR_FULL_ALLCOMPONENTS__1->SetBinContent(3,355.46);
   histoToy_MR_FULL_ALLCOMPONENTS__1->SetBinContent(4,103.78);
   histoToy_MR_FULL_ALLCOMPONENTS__1->SetBinContent(5,18.14);
   histoToy_MR_FULL_ALLCOMPONENTS__1->SetBinContent(6,2.02);
   histoToy_MR_FULL_ALLCOMPONENTS__1->SetBinContent(7,0.02);
   histoToy_MR_FULL_ALLCOMPONENTS__1->SetMinimum(0.5);
   histoToy_MR_FULL_ALLCOMPONENTS__1->SetMaximum(50000);
   histoToy_MR_FULL_ALLCOMPONENTS__1->SetEntries(166449);
   histoToy_MR_FULL_ALLCOMPONENTS__1->SetDirectory(0);
   histoToy_MR_FULL_ALLCOMPONENTS__1->SetStats(0);
   histoToy_MR_FULL_ALLCOMPONENTS__1->SetFillStyle(0);

   ci = TColor::GetColor("#000099");
   histoToy_MR_FULL_ALLCOMPONENTS__1->SetLineColor(ci);
   histoToy_MR_FULL_ALLCOMPONENTS__1->SetLineWidth(2);
   histoToy_MR_FULL_ALLCOMPONENTS__1->GetXaxis()->SetRange(1,7);
   histoToy_MR_FULL_ALLCOMPONENTS__1->GetXaxis()->SetLabelFont(42);
   histoToy_MR_FULL_ALLCOMPONENTS__1->GetXaxis()->SetLabelSize(0.035);
   histoToy_MR_FULL_ALLCOMPONENTS__1->GetXaxis()->SetTitleSize(0.035);
   histoToy_MR_FULL_ALLCOMPONENTS__1->GetXaxis()->SetTitleFont(42);
   histoToy_MR_FULL_ALLCOMPONENTS__1->GetYaxis()->SetTitle("Events");
   histoToy_MR_FULL_ALLCOMPONENTS__1->GetYaxis()->SetLabelFont(42);
   histoToy_MR_FULL_ALLCOMPONENTS__1->GetYaxis()->SetLabelSize(0.035);
   histoToy_MR_FULL_ALLCOMPONENTS__1->GetYaxis()->SetTitleSize(0.035);
   histoToy_MR_FULL_ALLCOMPONENTS__1->GetYaxis()->SetTitleFont(42);
   histoToy_MR_FULL_ALLCOMPONENTS__1->GetZaxis()->SetLabelFont(42);
   histoToy_MR_FULL_ALLCOMPONENTS__1->GetZaxis()->SetLabelSize(0.035);
   histoToy_MR_FULL_ALLCOMPONENTS__1->GetZaxis()->SetTitleSize(0.035);
   histoToy_MR_FULL_ALLCOMPONENTS__1->GetZaxis()->SetTitleFont(42);
   histoToy_MR_FULL_ALLCOMPONENTS__1->Draw("histsame");
   Double_t xAxis6[8] = {450, 550, 700, 900, 1200, 1600, 2500, 4000}; 
   
   TH1D *histoToySignal_MR_FULL_ALLCOMPONENTS = new TH1D("histoToySignal_MR_FULL_ALLCOMPONENTS","histoToySignal",7, xAxis6);
   histoToySignal_MR_FULL_ALLCOMPONENTS->SetStats(0);

   ci = TColor::GetColor("#666666");
   histoToySignal_MR_FULL_ALLCOMPONENTS->SetFillColor(ci);
   histoToySignal_MR_FULL_ALLCOMPONENTS->SetFillStyle(3005);
   histoToySignal_MR_FULL_ALLCOMPONENTS->SetLineStyle(2);
   histoToySignal_MR_FULL_ALLCOMPONENTS->SetLineWidth(2);
   histoToySignal_MR_FULL_ALLCOMPONENTS->GetXaxis()->SetTitle("M_{R} [GeV]");
   histoToySignal_MR_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoToySignal_MR_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoToySignal_MR_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoToySignal_MR_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoToySignal_MR_FULL_ALLCOMPONENTS->GetYaxis()->SetTitle("Events/(100 GeV)");
   histoToySignal_MR_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoToySignal_MR_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoToySignal_MR_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoToySignal_MR_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoToySignal_MR_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoToySignal_MR_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoToySignal_MR_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoToySignal_MR_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoToySignal_MR_FULL_ALLCOMPONENTS->Draw("histfsame");
   
   TLegend *leg = new TLegend(0.7,0.55,0.93,0.93,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("histoData_MR_FULL_ALLCOMPONENTS","Simulated Data","lep");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("histoToy_MR_FULL_ALLCOMPONENTSCOPY","Bkgd, #geq 1 b-tag","lpf");

   ci = TColor::GetColor("#ccccff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("histoToyTTj1b_MR_FULL_ALLCOMPONENTS","1 b-tag","l");

   ci = TColor::GetColor("#cc00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("histoToyTTj2b_MR_FULL_ALLCOMPONENTS","#geq 2 b-tag","l");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   TPaveText *pt = new TPaveText(0.25,0.67,0.7,0.93,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetLineColor(0);
   pt->SetTextAlign(21);
   pt->SetTextFont(42);
   pt->SetTextSize(0.062);
   TText *text = pt->AddText("CMS Simulation #sqrt{s} = 8 TeV");
   text = pt->AddText("t#bar{t}+jets BJetHS Box , #geq 1 b-tag");
   pt->Draw();
   pad1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: pad2
   pad2 = new TPad("pad2", "pad2",0,0,1,0.25);
   pad2->Draw();
   pad2->cd();
   pad2->Range(-215.625,-3.103774,4221.875,3.5);
   pad2->SetFillColor(0);
   pad2->SetBorderMode(0);
   pad2->SetBorderSize(2);
   pad2->SetLeftMargin(0.15);
   pad2->SetRightMargin(0.05);
   pad2->SetTopMargin(0);
   pad2->SetBottomMargin(0.47);
   pad2->SetFrameBorderMode(0);
   pad2->SetFrameBorderMode(0);
   Double_t xAxis7[8] = {450, 550, 700, 900, 1200, 1600, 2500, 4000}; 
   
   TH1D *histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide = new TH1D("histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide","",7, xAxis7);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(1,1);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(2,1);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(3,1);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(4,1);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(5,1);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(6,1);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(7,1);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(1,0.02323434);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(2,0.08818072);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(3,0.09583551);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(4,0.1948876);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(5,0.4603096);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(6,1.209975);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(7,50);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetMinimum(0);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetMaximum(3.5);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetEntries(166456);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetStats(0);

   ci = TColor::GetColor("#ccccff");
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetLineColor(ci);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetLineWidth(2);

   ci = TColor::GetColor("#ccccff");
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetMarkerColor(ci);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitle("M_{R} [GeV]");
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetRange(1,7);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelFont(42);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelOffset(0.02);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelSize(0.22);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleSize(0.22);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTickLength(0.07);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleOffset(0.97);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleFont(42);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitle("Data/Bkgd");
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetNdivisions(504);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelFont(42);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelSize(0.18);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleSize(0.22);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleOffset(0.2);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleFont(42);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelFont(42);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelSize(0.035);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleSize(0.035);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleFont(42);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->Draw("e2");
   Double_t xAxis8[8] = {450, 550, 700, 900, 1200, 1600, 2500, 4000}; 
   
   TH1D *histoData_MR_FULL_ALLCOMPONENTSDivide = new TH1D("histoData_MR_FULL_ALLCOMPONENTSDivide","histoData",7, xAxis8);
   histoData_MR_FULL_ALLCOMPONENTSDivide->SetBinContent(1,0.9690027);
   histoData_MR_FULL_ALLCOMPONENTSDivide->SetBinContent(2,1.105161);
   histoData_MR_FULL_ALLCOMPONENTSDivide->SetBinContent(3,0.9480673);
   histoData_MR_FULL_ALLCOMPONENTSDivide->SetBinContent(4,0.7323184);
   histoData_MR_FULL_ALLCOMPONENTSDivide->SetBinContent(5,0.8820287);
   histoData_MR_FULL_ALLCOMPONENTSDivide->SetBinContent(6,1.485149);
   histoData_MR_FULL_ALLCOMPONENTSDivide->SetBinError(1,0.0228714);
   histoData_MR_FULL_ALLCOMPONENTSDivide->SetBinError(2,0.0332916);
   histoData_MR_FULL_ALLCOMPONENTSDivide->SetBinError(3,0.05164452);
   histoData_MR_FULL_ALLCOMPONENTSDivide->SetBinError(4,0.08400268);
   histoData_MR_FULL_ALLCOMPONENTSDivide->SetBinError(5,0.2205072);
   histoData_MR_FULL_ALLCOMPONENTSDivide->SetBinError(6,0.8574509);
   histoData_MR_FULL_ALLCOMPONENTSDivide->SetEntries(3336);
   histoData_MR_FULL_ALLCOMPONENTSDivide->SetStats(0);
   histoData_MR_FULL_ALLCOMPONENTSDivide->SetLineWidth(2);
   histoData_MR_FULL_ALLCOMPONENTSDivide->SetMarkerStyle(20);
   histoData_MR_FULL_ALLCOMPONENTSDivide->GetXaxis()->SetTitle("M_{R} [GeV]");
   histoData_MR_FULL_ALLCOMPONENTSDivide->GetXaxis()->SetRange(1,7);
   histoData_MR_FULL_ALLCOMPONENTSDivide->GetXaxis()->SetLabelFont(42);
   histoData_MR_FULL_ALLCOMPONENTSDivide->GetXaxis()->SetLabelSize(0.035);
   histoData_MR_FULL_ALLCOMPONENTSDivide->GetXaxis()->SetTitleSize(0.035);
   histoData_MR_FULL_ALLCOMPONENTSDivide->GetXaxis()->SetTitleFont(42);
   histoData_MR_FULL_ALLCOMPONENTSDivide->GetYaxis()->SetTitle("Events/(100 GeV)");
   histoData_MR_FULL_ALLCOMPONENTSDivide->GetYaxis()->SetLabelFont(42);
   histoData_MR_FULL_ALLCOMPONENTSDivide->GetYaxis()->SetLabelSize(0.035);
   histoData_MR_FULL_ALLCOMPONENTSDivide->GetYaxis()->SetTitleSize(0.035);
   histoData_MR_FULL_ALLCOMPONENTSDivide->GetYaxis()->SetTitleFont(42);
   histoData_MR_FULL_ALLCOMPONENTSDivide->GetZaxis()->SetLabelFont(42);
   histoData_MR_FULL_ALLCOMPONENTSDivide->GetZaxis()->SetLabelSize(0.035);
   histoData_MR_FULL_ALLCOMPONENTSDivide->GetZaxis()->SetTitleSize(0.035);
   histoData_MR_FULL_ALLCOMPONENTSDivide->GetZaxis()->SetTitleFont(42);
   histoData_MR_FULL_ALLCOMPONENTSDivide->Draw("pesame");
   Double_t xAxis9[8] = {450, 550, 700, 900, 1200, 1600, 2500, 4000}; 
   
   TH1D *histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide = new TH1D("histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide","",7, xAxis9);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(1,1);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(2,1);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(3,1);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(4,1);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(5,1);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(6,1);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(7,1);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(1,0.02323434);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(2,0.08818072);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(3,0.09583551);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(4,0.1948876);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(5,0.4603096);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(6,1.209975);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(7,50);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetMinimum(0);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetMaximum(3.5);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetEntries(166456);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetStats(0);

   ci = TColor::GetColor("#ccccff");
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetLineColor(ci);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetLineWidth(2);

   ci = TColor::GetColor("#ccccff");
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->SetMarkerColor(ci);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitle("M_{R} [GeV]");
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetRange(1,7);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelFont(42);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelOffset(0.02);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelSize(0.22);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleSize(0.22);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTickLength(0.07);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleOffset(0.97);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleFont(42);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitle("Data/Bkgd");
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetNdivisions(504);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelFont(42);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelSize(0.18);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleSize(0.22);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleOffset(0.2);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleFont(42);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelFont(42);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelSize(0.035);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleSize(0.035);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleFont(42);
   histoToy_MR_FULL_ALLCOMPONENTSCOPYDivide->Draw("axissame");
   pad2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
