{
//=========Macro generated from canvas: c1/c1
//=========  (Wed Feb 12 21:48:06 2014) by ROOT version5.34/13
   TCanvas *c1 = new TCanvas("c1", "c1",0,22,500,400);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->SetHighLightColor(2);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: pad1
   TPad *pad1 = new TPad("pad1", "pad1",0,0.25,1,1);
   pad1->Draw();
   pad1->cd();
   pad1->Range(-0.1625,-0.30103,1.5875,4.313885);
   pad1->SetFillColor(0);
   pad1->SetBorderMode(0);
   pad1->SetBorderSize(2);
   pad1->SetLogy();
   pad1->SetLeftMargin(0.15);
   pad1->SetRightMargin(0.05);
   pad1->SetTopMargin(0.05);
   pad1->SetBottomMargin(0);
   pad1->SetFrameBorderMode(0);
   pad1->SetFrameBorderMode(0);
   Double_t xAxis10[8] = {0.1, 0.2, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoToy_Rsq_FULL_ALLCOMPONENTSCOPY = new TH1D("histoToy_Rsq_FULL_ALLCOMPONENTSCOPY","histoToy",7, xAxis10);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->SetBinContent(1,2754.22);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->SetBinContent(2,449.9);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->SetBinContent(3,97.1);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->SetBinContent(4,21);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->SetBinContent(5,5.1);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->SetBinContent(6,1.54);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->SetBinContent(7,0.12);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->SetBinError(1,104.7439);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->SetBinError(2,36.15897);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->SetBinError(3,17.80547);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->SetBinError(4,7.843781);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->SetBinError(5,3.643644);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->SetBinError(6,1.48988);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->SetBinError(7,1);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->SetMinimum(0.5);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->SetMaximum(12109.86);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->SetEntries(166449);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ccccff");
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->SetLineColor(ci);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->SetLineWidth(2);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetRange(1,7);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetLabelFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetLabelOffset(0.16);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetLabelSize(0.06);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetTitleSize(0.06);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetTitleOffset(0.8);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->GetXaxis()->SetTitleFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetTitle("Events");
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetLabelFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetLabelSize(0.06);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetTitleSize(0.08);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetTitleOffset(0.7);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->GetYaxis()->SetTitleFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->GetZaxis()->SetLabelFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->GetZaxis()->SetLabelSize(0.035);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->GetZaxis()->SetTitleSize(0.035);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->GetZaxis()->SetTitleFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPY->Draw("e2");
   Double_t xAxis11[8] = {0.1, 0.2, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS = new TH1D("histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS","histoToyTTj2b",7, xAxis11);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->SetBinContent(1,1583.26);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->SetBinContent(2,260.96);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->SetBinContent(3,54.54);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->SetBinContent(4,11.64);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->SetBinContent(5,2.78);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->SetBinContent(6,0.76);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->SetBinContent(7,0.06);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->SetBinError(1,39.7902);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->SetBinError(2,16.15426);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->SetBinError(3,7.38512);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->SetBinError(4,3.411744);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->SetBinError(5,1.667333);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->SetBinError(6,1);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->SetBinError(7,1);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->SetEntries(95700);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->SetStats(0);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->SetFillStyle(0);

   ci = TColor::GetColor("#ff0000");
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->SetLineColor(ci);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->SetLineWidth(2);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->GetXaxis()->SetTitle("R^{2}");
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->GetYaxis()->SetTitle("Events/(0.100)");
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS->Draw("histsame");
   Double_t xAxis12[8] = {0.1, 0.2, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS = new TH1D("histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS","histoToyTTj1b",7, xAxis12);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->SetBinContent(1,1170.96);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->SetBinContent(2,188.94);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->SetBinContent(3,42.56);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->SetBinContent(4,9.36);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->SetBinContent(5,2.32);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->SetBinContent(6,0.78);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->SetBinContent(7,0.06);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->SetBinError(1,34.21929);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->SetBinError(2,13.74554);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->SetBinError(3,6.523803);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->SetBinError(4,3.059412);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->SetBinError(5,1.523155);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->SetBinError(6,1);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->SetBinError(7,1);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->SetEntries(70749);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->SetStats(0);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->SetFillStyle(0);

   ci = TColor::GetColor("#cc00ff");
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->SetLineColor(ci);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->SetLineWidth(2);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->GetXaxis()->SetTitle("R^{2}");
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->GetYaxis()->SetTitle("Events/(0.100)");
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS->Draw("histsame");
   Double_t xAxis13[8] = {0.1, 0.2, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoData_Rsq_FULL_ALLCOMPONENTS = new TH1D("histoData_Rsq_FULL_ALLCOMPONENTS","histoData",7, xAxis13);
   histoData_Rsq_FULL_ALLCOMPONENTS->SetBinContent(1,2719);
   histoData_Rsq_FULL_ALLCOMPONENTS->SetBinContent(2,467);
   histoData_Rsq_FULL_ALLCOMPONENTS->SetBinContent(3,106);
   histoData_Rsq_FULL_ALLCOMPONENTS->SetBinContent(4,28);
   histoData_Rsq_FULL_ALLCOMPONENTS->SetBinContent(5,8);
   histoData_Rsq_FULL_ALLCOMPONENTS->SetBinContent(7,1);
   histoData_Rsq_FULL_ALLCOMPONENTS->SetBinError(1,52.14403);
   histoData_Rsq_FULL_ALLCOMPONENTS->SetBinError(2,21.61018);
   histoData_Rsq_FULL_ALLCOMPONENTS->SetBinError(3,10.29563);
   histoData_Rsq_FULL_ALLCOMPONENTS->SetBinError(4,5.291503);
   histoData_Rsq_FULL_ALLCOMPONENTS->SetBinError(5,2.828427);
   histoData_Rsq_FULL_ALLCOMPONENTS->SetBinError(7,1);
   histoData_Rsq_FULL_ALLCOMPONENTS->SetEntries(3329);
   histoData_Rsq_FULL_ALLCOMPONENTS->SetStats(0);
   histoData_Rsq_FULL_ALLCOMPONENTS->SetLineWidth(2);
   histoData_Rsq_FULL_ALLCOMPONENTS->SetMarkerStyle(20);
   histoData_Rsq_FULL_ALLCOMPONENTS->GetXaxis()->SetTitle("R^{2}");
   histoData_Rsq_FULL_ALLCOMPONENTS->GetXaxis()->SetRange(1,6);
   histoData_Rsq_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoData_Rsq_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoData_Rsq_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoData_Rsq_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoData_Rsq_FULL_ALLCOMPONENTS->GetYaxis()->SetTitle("Events/(0.100)");
   histoData_Rsq_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoData_Rsq_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoData_Rsq_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoData_Rsq_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoData_Rsq_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoData_Rsq_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoData_Rsq_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoData_Rsq_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoData_Rsq_FULL_ALLCOMPONENTS->Draw("pesame");
   Double_t xAxis14[8] = {0.1, 0.2, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoToy_Rsq_FULL_ALLCOMPONENTS__2 = new TH1D("histoToy_Rsq_FULL_ALLCOMPONENTS__2","histoToy",7, xAxis14);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->SetBinContent(1,2754.22);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->SetBinContent(2,449.9);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->SetBinContent(3,97.1);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->SetBinContent(4,21);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->SetBinContent(5,5.1);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->SetBinContent(6,1.54);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->SetBinContent(7,0.12);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->SetMinimum(0.5);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->SetMaximum(50000);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->SetEntries(166449);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->SetDirectory(0);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->SetStats(0);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->SetFillStyle(0);

   ci = TColor::GetColor("#000099");
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->SetLineColor(ci);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->SetLineWidth(2);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->GetXaxis()->SetRange(1,6);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->GetXaxis()->SetLabelFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->GetXaxis()->SetLabelSize(0.035);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->GetXaxis()->SetTitleSize(0.035);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->GetXaxis()->SetTitleFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->GetYaxis()->SetTitle("Events");
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->GetYaxis()->SetLabelFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->GetYaxis()->SetLabelSize(0.035);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->GetYaxis()->SetTitleSize(0.035);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->GetYaxis()->SetTitleFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->GetZaxis()->SetLabelFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->GetZaxis()->SetLabelSize(0.035);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->GetZaxis()->SetTitleSize(0.035);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->GetZaxis()->SetTitleFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTS__2->Draw("histsame");
   Double_t xAxis15[8] = {0.1, 0.2, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoToySignal_Rsq_FULL_ALLCOMPONENTS = new TH1D("histoToySignal_Rsq_FULL_ALLCOMPONENTS","histoToySignal",7, xAxis15);
   histoToySignal_Rsq_FULL_ALLCOMPONENTS->SetStats(0);

   ci = TColor::GetColor("#666666");
   histoToySignal_Rsq_FULL_ALLCOMPONENTS->SetFillColor(ci);
   histoToySignal_Rsq_FULL_ALLCOMPONENTS->SetFillStyle(3005);
   histoToySignal_Rsq_FULL_ALLCOMPONENTS->SetLineStyle(2);
   histoToySignal_Rsq_FULL_ALLCOMPONENTS->SetLineWidth(2);
   histoToySignal_Rsq_FULL_ALLCOMPONENTS->GetXaxis()->SetTitle("R^{2}");
   histoToySignal_Rsq_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoToySignal_Rsq_FULL_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoToySignal_Rsq_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoToySignal_Rsq_FULL_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoToySignal_Rsq_FULL_ALLCOMPONENTS->GetYaxis()->SetTitle("Events/(0.100)");
   histoToySignal_Rsq_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoToySignal_Rsq_FULL_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoToySignal_Rsq_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoToySignal_Rsq_FULL_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoToySignal_Rsq_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoToySignal_Rsq_FULL_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoToySignal_Rsq_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoToySignal_Rsq_FULL_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoToySignal_Rsq_FULL_ALLCOMPONENTS->Draw("histfsame");
   
   TLegend *leg = new TLegend(0.7,0.55,0.93,0.93,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("histoData_Rsq_FULL_ALLCOMPONENTS","Simulated Data","lep");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("histoToy_Rsq_FULL_ALLCOMPONENTSCOPY","Bkgd, #geq 1 b-tag","lpf");

   ci = TColor::GetColor("#ccccff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("histoToyTTj1b_Rsq_FULL_ALLCOMPONENTS","1 b-tag","l");

   ci = TColor::GetColor("#cc00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("histoToyTTj2b_Rsq_FULL_ALLCOMPONENTS","#geq 2 b-tag","l");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   TPaveText *pt = new TPaveText(0.25,0.67,0.7,0.93,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetLineColor(0);
   pt->SetTextAlign(21);
   pt->SetTextFont(42);
   pt->SetTextSize(0.062);
   TText *text = pt->AddText("CMS Simulation #sqrt{s} = 8 TeV");
   text = pt->AddText("t#bar{t}+jets BJetHS Box , #geq 1 b-tag");
   pt->Draw();
   pad1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: pad2
   pad2 = new TPad("pad2", "pad2",0,0,1,0.25);
   pad2->Draw();
   pad2->cd();
   pad2->Range(-0.1625,-3.103774,1.5875,3.5);
   pad2->SetFillColor(0);
   pad2->SetBorderMode(0);
   pad2->SetBorderSize(2);
   pad2->SetLeftMargin(0.15);
   pad2->SetRightMargin(0.05);
   pad2->SetTopMargin(0);
   pad2->SetBottomMargin(0.47);
   pad2->SetFrameBorderMode(0);
   pad2->SetFrameBorderMode(0);
   Double_t xAxis16[8] = {0.1, 0.2, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide = new TH1D("histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide","",7, xAxis16);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(1,1);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(2,1);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(3,1);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(4,1);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(5,1);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(6,1);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(7,1);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(1,0.03803033);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(2,0.08037113);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(3,0.1833725);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(4,0.3735134);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(5,0.7144399);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(6,0.9674545);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(7,8.333333);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetMinimum(0);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetMaximum(3.5);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetEntries(166456);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetStats(0);

   ci = TColor::GetColor("#ccccff");
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetLineColor(ci);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetLineWidth(2);

   ci = TColor::GetColor("#ccccff");
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetMarkerColor(ci);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitle("R^{2}");
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetRange(1,7);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelOffset(0.02);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelSize(0.22);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleSize(0.22);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTickLength(0.07);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleOffset(0.97);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitle("Data/Bkgd");
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetNdivisions(504);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelSize(0.18);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleSize(0.22);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleOffset(0.2);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelSize(0.035);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleSize(0.035);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->Draw("e2");
   Double_t xAxis17[8] = {0.1, 0.2, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoData_Rsq_FULL_ALLCOMPONENTSDivide = new TH1D("histoData_Rsq_FULL_ALLCOMPONENTSDivide","histoData",7, xAxis17);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->SetBinContent(1,0.9872124);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->SetBinContent(2,1.038008);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->SetBinContent(3,1.091658);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->SetBinContent(4,1.333333);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->SetBinContent(5,1.568627);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->SetBinContent(7,8.333333);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->SetBinError(1,0.01893241);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->SetBinError(2,0.0480333);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->SetBinError(3,0.1060312);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->SetBinError(4,0.2519763);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->SetBinError(5,0.5545936);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->SetBinError(7,8.333333);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->SetEntries(3336);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->SetStats(0);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->SetLineWidth(2);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->SetMarkerStyle(20);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->GetXaxis()->SetTitle("R^{2}");
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->GetXaxis()->SetRange(1,6);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->GetXaxis()->SetLabelFont(42);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->GetXaxis()->SetLabelSize(0.035);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->GetXaxis()->SetTitleSize(0.035);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->GetXaxis()->SetTitleFont(42);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->GetYaxis()->SetTitle("Events/(0.100)");
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->GetYaxis()->SetLabelFont(42);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->GetYaxis()->SetLabelSize(0.035);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->GetYaxis()->SetTitleSize(0.035);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->GetYaxis()->SetTitleFont(42);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->GetZaxis()->SetLabelFont(42);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->GetZaxis()->SetLabelSize(0.035);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->GetZaxis()->SetTitleSize(0.035);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->GetZaxis()->SetTitleFont(42);
   histoData_Rsq_FULL_ALLCOMPONENTSDivide->Draw("pesame");
   Double_t xAxis18[8] = {0.1, 0.2, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide = new TH1D("histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide","",7, xAxis18);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(1,1);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(2,1);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(3,1);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(4,1);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(5,1);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(6,1);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinContent(7,1);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(1,0.03803033);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(2,0.08037113);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(3,0.1833725);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(4,0.3735134);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(5,0.7144399);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(6,0.9674545);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetBinError(7,8.333333);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetMinimum(0);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetMaximum(3.5);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetEntries(166456);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetStats(0);

   ci = TColor::GetColor("#ccccff");
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetLineColor(ci);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetLineWidth(2);

   ci = TColor::GetColor("#ccccff");
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->SetMarkerColor(ci);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitle("R^{2}");
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetRange(1,7);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelOffset(0.02);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelSize(0.22);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleSize(0.22);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTickLength(0.07);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleOffset(0.97);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitle("Data/Bkgd");
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetNdivisions(504);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelSize(0.18);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleSize(0.22);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleOffset(0.2);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelSize(0.035);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleSize(0.035);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleFont(42);
   histoToy_Rsq_FULL_ALLCOMPONENTSCOPYDivide->Draw("axissame");
   pad2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
